[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
    # This line is the magic bullet:
    "-C", "link-arg=-z", "-C", "link-arg=keep-section=.boot2",
]